### ISSUE TITLE
pbp_status is "failing" since 2022-07-28

### ISSUE THREAD

**Issue by iorparask** [nflverse/nflverse-data#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### Describe the bug

It appears that PBP data are failing since end of July. Of course, there wasn't any official game until now but since yesterday we had the beginning of the new season, I was hoping that we could see PBP data for the games once they were concluded. 
Another factor which I'm not sure about, is whether the pbp data supposed to be updated constantly or in batches.
Thank you

### Reprex

load_pbp(2022)

### Expected Behavior

Return PBP data for concluded 2022 games

### nflverse_sitrep

Sorry cannot execute right now, but I think it is not important.

### screenshots

```markdown
- OS:
- Node:
- npm:
```

**Comment by tanho63** [comment]
failures before today are just actions overzealously trying to fetch 2022 games, but there is a known issue

https://twitter.com/benbbaldwin/status/1568076470064484352?s=46&t=x9i5JCmRPJq7juc9WjvSLg

**Comment by tanho63** [comment]
Base play data is working now, but data quality issues remain. Closing this issue for now.
