### ISSUE TITLE
Dataset used in "Efficient Data Analysis on Larger-than-Memory Data with DuckDB and Arrow"

### ISSUE THREAD

**Issue by danielbellhv** [nflverse/nflverse-data#11]
Hi,

Can I possibly have a link to the nflverse dataset used in this [presentation video](https://youtu.be/LvTX1ZAZy6M), at the linked timestamp, please?

Kind Regards,
Daniel Bell

**Comment by tanho63** [comment]
No timestamp, but you can find all datasets in the releases here https://github.com/nflverse/nflverse-data/releases

**Comment by danielbellhv** [comment]
Sorry try this timestamp https://youtu.be/LvTX1ZAZy6M
