### ISSUE TITLE
include scrape source for rosters in documentation

### ISSUE THREAD

**Issue by matthewdwood82** [nflverse/nflverse-data#15]
1. **Is your feature request related to a problem? Please describe.**
The source of the data which populates the individuals on the 53-man roster for a given week is not clear.

2. **Describe the solution you'd like**
Add 1-2 lines in load_rosters() or a dependency that indicates the source for this data.

3. **Describe alternatives you've considered**
A field in the dataframe that explicitly references the datasource that was used to determine the player was on the 53-man for this week and year.

4. **Additional context**
Had a friend ask me about source in a sports analytics chat I belong to, I did not have a satisfying answer for him.

**Comment by tanho63** [comment]
Hmm. It's a bit of a mix of things so not a straightforward question to answer. Is the hope to replicate it or to cite it?

**Comment by matthewdwood82** [comment]
Desire is to understand veracity of roster data in the package at kickoff for relevant week and year, especially for the past 1-2 year's data. Goal is to use it for an anti-points league, to validate whether a rostered player could have accumulated fantasy points.

**Comment by tanho63** [comment]
Closing this as not planned. fwiw in an anti-points league I'd probably award positive points for every snap and negative points for every stat accumulated, that would up the challenge to finding the really irrelevant players on the field
