### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by EduardoSanchezZ** [nflverse/nflverse-data#16]
I'm using your data for a school project and i want to cite your repository; i think it would be cool to have a Citation.md

**Comment by tanho63** [comment]
For the moment you will need to cite one of the R packages - any of these are fine: https://nflverse.nflverse.com/authors.html#citation, https://nflreadr.nflverse.com/authors.html#citation,
https://www.nflfastr.com/authors.html#citation

depending on what you’re using

**Comment by EduardoSanchezZ** [comment]
Thanks for the help & and i'm a big fan of your work
