### ISSUE TITLE
[BUG] Anthony Brown BAL QB mapped to wrong pfr_player_id

### ISSUE THREAD

**Issue by soricinae** [nflverse/nflverse-data#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

na

### Describe the bug

Baltimore Ravens QB Anthony Brown is incorrectly mapped to Dallas Cowboys CB Anthony Brown

### Reprex

```r
Repro:
1. Download this file: `https://github.com/nflverse/nflverse-data/releases/download/snap_counts/snap_counts_2022.csv`
2. Filter to: {game_id: 2022_14_BAL_PIT, player: "Anthony Brown"}
Actual: pfr_player_id = BrowAn02
```

### Expected Behavior

Expected: pfr_player_id = BrowAn06

### nflverse_sitrep

```r
na
```

### Screenshots

```markdown
na
```

### Additional context

na

**Comment by tanho63** [comment]
Hmm. We don't manually map these. I can delete and queue it for re-scrape to see if PFR corrected the issue on their end

**Comment by tanho63** [comment]
Resolved 
```
R> nflreadr::load_snap_counts(2022) |> 
+++    dplyr::filter(game_id == "2022_14_BAL_PIT", player == "Anthony Brown") |> 
+++    dplyr::select(player, pfr_player_id)
── nflverse snap counts ─────────────────────────────────────────────────────────────────────────
ℹ Data updated: 2023-02-13 13:28:12 EST
# A tibble: 1 × 2
  player        pfr_player_id
  <chr>         <chr>        
1 Anthony Brown BrowAn06 
```
