### ISSUE TITLE
[BUG] Status badges are broken

### ISSUE THREAD

**Issue by alecglen** [nflverse/nflverse-data#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

NA

### Describe the bug

![image](https://user-images.githubusercontent.com/28493454/218610585-a7ece614-db66-4e64-bb91-fa406b11820d.png)

### Reprex

```r
NA
```

### Expected Behavior

NA

### nflverse_sitrep

```r
NA
```

### Additional context

This seems to be the cause - https://github.com/badges/shields/issues/8671

**Comment by tanho63** [comment]
Thanks! On the long list of offseason maintenance.

**Comment by tanho63** [comment]
Should now be resolved.
