### ISSUE TITLE
[BUG] draft_picks release is missing 2017 and newer

### ISSUE THREAD

**Issue by alecglen** [nflverse/nflverse-data#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

NA

### Describe the bug

The data in the draft_picks release (specifically, parquet and csv checked) is cut off after 2016.

### Reprex

```py
from pandas import read_csv

picks = read_csv('https://github.com/nflverse/nflverse-data/releases/download/draft_picks/draft_picks.csv')
print(picks.season.max())
```

### Expected Behavior

2022

### nflverse_sitrep

```r
NA
```

**Comment by tanho63** [comment]
Resolved by nflverse/nflverse-pfr@93ea6ebcbb495ef42a95af72ee8662a5f4cf0c5a
