### ISSUE TITLE
Include defense player stats in player stats releases

### ISSUE THREAD

**Issue by christianlohr9** [nflverse/nflverse-data#25]
I wanted to make a PR to ffscrapr to help getting the `ff_scoringhistory()` for IDP.
Since @tanho63 uses the static player stat files it'd be an easy and cool way to have the defense player stats file in https://github.com/nflverse/nflverse-data/releases.

With the `aggregate_game_stats_def()` it should be possible to store them.

Love you all ❤️

**Comment by mrcaseb** [comment]
Done.
