### ISSUE TITLE
[question] NFL Data Update Schedule

### ISSUE THREAD

**Issue by Snixells** [nflverse/nflverse-data#29]
Hello! I'd like to use the NFL data for weekly game statistics. When is this data updated? For instance, when can I access the play-by-play for Week 1 of the 2023 season? I couldn't find this info elsewhere. Thank you very much in advance!

**Comment by john-b-edwards** [comment]
Week 1 of the 2023 NFL season begins September 7, 2023 when the Chiefs face the Lions. nflverse data typically updates the morning after each game.
