### ISSUE TITLE
play_by_play_2023 has incorrect old_game_id for Week 15 2023

### ISSUE THREAD

**Issue by RGAlexander216** [nflverse/nflverse-data#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I have cleared my nflverse cache and the issue persists.

### What version of the package do you have?

1.0.3

### Describe the bug

As stated in the title, the old_game_id is not correct for all of the week 15 games of the 2023 season preventing the ability to easily join to the pbp_participation data to the play_by_play data. The Play By Play 2023 data has old_game_id values beginning with 2022 whereas the PBP Participation has the correctly formatted version starting with 2023. See images provided.

### Reprex

```r
Not applicable, bad data is the source of the bug as illustrated.
```

### Expected Behavior

A successful join of the data based on the old_game_id and play_id fields.

### nflverse_sitrep

```r
NA
```

### Screenshots

PBP Participation for week 15 of 2023:
![image](https://github.com/nflverse/nflverse-data/assets/20406603/1c18abc5-7f9f-4b47-95f9-ff2d21bee6ab)

Play By Play for week 15 of 2023:
![image](https://github.com/nflverse/nflverse-data/assets/20406603/539fa6b0-701a-4935-a507-395466191308)

**Comment by mrcaseb** [comment]
This has been resolved
