### ISSUE TITLE
[BUG] load_contracts() returns empty dataframe

### ISSUE THREAD

**Issue by thomasjosephwilson** [nflverse/nflverse-data#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I have cleared my nflverse cache and the issue persists.

### What version of the package do you have?

1.4.1

### Describe the bug

load_contracts() returns empty dataframe, it worked last night.

**ERROR:**

Warning messages:
1: In readRDS(con) :
  cannot open URL 'https://github.com/nflverse/nflverse-data/releases/download/contracts/historical_contracts.rds': HTTP status was '404 Not Found'
2: Failed to readRDS from
<https://github.com/nflverse/nflverse-data/releases/download/contracts/historical_contracts.rds> 
> 

looking at https://github.com/nflverse/nflverse-data/releases?page=2 it seems like historical_contracts was updated 14 hours ago which is causing the error, as historical_contracts.rds does not exist for download anymore, only historical_contracts.qs and historical_contracts.csv.gz
 

### Reprex

```r
library(tidyverse)
library(nflreadr)

df <- load_contracts(file_type = getOption("nflreadr.prefer", default = "rds"))

df returns 0x0 tibble
```

### Expected Behavior

a full dataframe of contracts

### nflverse_sitrep

```r
NA
```

**Comment by tanho63** [comment]
Looks like a random error - https://github.com/nflverse/rotc/actions/runs/10503604209/job/29097293454#step:5:67 - @mrcaseb we should probably figure out how to get system2 to throw an error if it fails to upload

**Comment by tanho63** [comment]
rerunning the job now, progress here: https://github.com/nflverse/rotc/actions/runs/10518128506/job/29143435762 should be back in a couple of minutes :crossed_fingers:

**Comment by mrcaseb** [comment]
> Looks like a random error - https://github.com/nflverse/rotc/actions/runs/10503604209/job/29097293454#step:5:67 - @mrcaseb we should probably figure out how to get system2 to throw an error if it fails to upload

Yes, this was supposed to error. Not sure why it throws a warning only. Will look into it.

**Comment by mrcaseb** [comment]
Data is back
