### ISSUE TITLE
[FEATURE REQ] Archive data more frequently during season

### ISSUE THREAD

**Issue by dschuler36** [nflverse/nflverse-data#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Getting the latest `depth_chart` data Thursday is a little late when trying to create stat predictions for the upcoming week. Most fantasy players are adjusting lineups starting Tuesday morning so it'd be great if datasets like `depth_chart` could be refreshed daily during the season so that the latest data is always available. I'm happy to help PR this if there's interest.

### Describe the solution you'd like

Datasets like `depth_chart` are refreshed daily during the NFL season.

### Additional context

I'm building stat predictions using this data and `depth_chart` data is a key piece of my prediction, so I don't want to release any predictions until that is refreshed for the week. This means I won't be able to get predictions out til Thursday instead of Tuesday.

Thanks so much for this project, by the way. It's really great to have such a high quality dataset available.

**Comment by tanho63** [comment]
https://github.com/nflverse/nflverse-rosters/blob/3637c34ed6dce797be59caae16271634161ab3a3/.github/workflows/update_depth_charts.yaml#L3

Depth charts are updated daily at 7:00 UTC

**Comment by dschuler36** [comment]
oh my bad! I was going off the cron in the github actions yaml. Thanks!

**Comment by tanho63** [comment]
Ah, in this repo? We archive all data in the github releases once a week in-season. Jobs generally have their own schedule.

**Comment by dschuler36** [comment]
yeah, sorry. was referring to this: https://github.com/nflverse/nflverse-data/blob/main/.github/workflows/run_archive.yaml#L4 

good to know these will be daily though! Do you have any idea when the first 2024 depth chart will be published?

**Comment by john-b-edwards** [comment]
@dschuler36 We pull depth charts from the NFL API. Rather frustratingly, it typically takes until _after_ week one games for these depth charts to populate in the API--then moving forward, each week's depth charts are available ahead of that week's games. So, the typical timeline is:

Week 1 games are played

Week 1 and 2 depth charts become available in the API

Week 2 games are played

I understand that this isn't ideal, unfortunately, we don't produce the depth charts ourselves, and we're at the mercy of the NFL API on this one.

**Comment by dschuler36** [comment]
thanks for the details, John! No worries, I can compile manually for now until they're available. Thanks for all the help
