### ISSUE TITLE
[BUG] season 1999 week 1 missing "1999_01_BAL_STL"

### ISSUE THREAD

**Issue by ak47twq** [nflverse/nflverse-data#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I have cleared my nflverse cache and the issue persists.

### What version of the package do you have?

nflfastR 4.6.1

### Describe the bug

season 1999 week 1 missing "1999_01_BAL_STL"

### Reprex

```r
test<-pbp%>%
  #filter(season_type=="REG") %>%	 
  #filter(season_type=="POST") %>%
  #filter(game_id=="1999_01_BAL_STL") %>%
  filter(season==1999,week==1) %>%
  select(game_id,season, week, desc,fixed_drive) %>%
  collect()
  
 test01<-test%>%
 group_by(game_id)%>%
 summarize(plays=n())
```
```


### Expected Behavior

season 1999 week 1 has "1999_01_BAL_STL"

### nflverse_sitrep

```r
NA
```

**Comment by mrcaseb** [comment]
That's a known issue. The data is missing in our source so we can't do anything about that. https://github.com/nflverse/nflfastR/blob/master/R/helper_scrape_gc.R#L22C3-L24C4
