### ISSUE TITLE
[FEATURE REQ] PFR_IDs for OL / defensive positions

### ISSUE THREAD

**Issue by kunalsingh23** [nflverse/nflverse-data#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Would love to be able to connect gsis_id's with pfr_ids. The one mututal connection (which works a lot of the time) is going between rosters <> snap counts tables. Rosters has both gsis and pfr_id which I believe is the only table that does. Once we can connect the gsis, it's easy to get all the other sources.

### Describe the solution you'd like

I'm not sure why exactly they are missing, I'm guessing faulty join's on the backend? Mostly missing for OL players, but some defensive players that do have sports ref IDs. There are some (now) significant placers that get a few touches a game that don't have the IDs linked, like Carson Steele. 

Example: https://www.pro-football-reference.com/players/W/WyliAn00.htm

### Describe alternatives you've considered

Isn't a fault, everything generally works but I don't get all the players in my joins if I'm building things off the snap counts file. 

### Additional context

nflreadr::load_rosters() %>%
    filter(is.na(pfr_id)) %>%
    select(position) %>%
    table()

**Comment by mrcaseb** [comment]
Implemented in https://github.com/nflverse/nflverse-players

The dataset currently is located the players_components release and nflreadr will load it through load_players in the next offseason.
