### ISSUE TITLE
Request: Field Orientation for Play by Play Data

### ISSUE THREAD

**Issue by FrankS136** [nflverse/nflverse-data#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I am looking to create a viz using the NFL pbp data to map Touchdowns in each endzone. The frustrating part is the lack of orientation available to accurately depict this. I have search ESPN, Pro_football, and NFL_data_py. The closest I have is knowledge of who kicks off at the begining of each half. Unfortunately the Coin toss outcome determines whether the winner kicks, recieves, deferrs, or picks endzone direction. I have not had any luck finding this info. Closest I have gotten is Pro_football game logs will say who won the kickoff. For an example it may say "Patriots win coin toss and defer" This does not tell us orientation picked by the other team in the first half. Also the Pro-football gmaelog is the only location for the winner, NFL_data_py first record per game description shows "GAME" rather than those important details in the Pro-football website

### Describe the solution you'd like

Most directly, the below is all I need to be added to NFL pbp data
1. Endzone direction: (ex. North/ South for Gillette Stadium)

Indrectly, based on Cointoss I can determine the direction

1. Coin toss winner
2. Winner decision:( Kickoff, recieve, defer, endzone direction)
3. Loser decision( if winner chooses kickoff, the loser picks direction)
4. Deferred indicator
5. Deferrer Decision( if winner deferred)
6. Second Half Decision 1 (kcik, receive, direction)
7. Second half decision 2 (kick, receive, direction)

### Describe alternatives you've considered

This does not need to be in PbP data, but could just be fields associated with each game ID and by quarter

**Comment by mrcaseb** [comment]
I am not aware of any data source that hosts this type of information. We are always open for pull requests if you manage to create this data. This is not within the scope of any nflverse maintainer so I close it for now
