### ISSUE TITLE
ESPN QBR Data Missing Since Week 10

### ISSUE THREAD

**Issue by StoneMasons4106** [nflverse/nflverse-data#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### If this is a data issue, have you tried clearing your nflverse cache?

I am not using an nflverse R package (nflreadr, nflfastR) to access this data.

### What version of the package do you have?

nfl-data-py==0.3.3

### Describe the bug

When running the import_qbr() function from nfl-data-py, no data from the current year is returned, even though the data is available via ESPN [here](https://www.espn.com/nfl/qbr).

### Reprex

```r
import nfl_data_py as nfl

qbr_data = nfl.import_qbr([2024])
qbr_data.to_csv('qbr.csv')
```

This returns an empty csv with the defaults for level being 'nfl' and season being 'regular'.
```


### Expected Behavior

I expected to receive up to date current QBR ratings and standings so far this year.

### nflverse_sitrep

```r
NA
```

**Comment by StoneMasons4106** [comment]
I apologize, there is a current issue already created for this here: https://github.com/nflverse/nfl_data_py/issues/114

I do believe that the issue is rooted in the espnscrapeR .github/update_qbr.yaml file not running as intended, but I will leave this to more qualified individuals.

**Comment by alecglen** [comment]
Keeping this open as a separate issue to troubleshoot the recent lack of QBR data in espnscrapeR-data.

The nfl_data_py issue you linked is specifically about updating the function's data source from espnscrapeR-data's data folder to the corresponding nflverse-data feed.

**Comment by mrcaseb** [comment]
Workflow fixed

**Comment by StoneMasons4106** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Have you installed the latest development version of the package(s) in question?
> * [x]  I have installed the latest development version of the package.
> 
> ### If this is a data issue, have you tried clearing your nflverse cache?
> I am not using an nflverse R package (nflreadr, nflfastR) to access this data.
> 
> ### What version of the package do you have?
> nfl-data-py==0.3.3
> 
> ### Describe the bug
> When running the import_qbr() function from nfl-data-py, no data from the current year is returned, even though the data is available via ESPN [here](https://www.espn.com/nfl/qbr).
> 
> ### Reprex
> ```r
> import nfl_data_py as nfl
> 
> qbr_data = nfl.import_qbr([2024])
> qbr_data.to_csv('qbr.csv')
> ```
> 
> This returns an empty csv with the defaults for level being 'nfl' and season being 'regular'.
> 
> ```
> 
> 
> ### Expected Behavior
> 
> I expected to receive up to date current QBR ratings and standings so far this year.
> 
> ### nflverse_sitrep
> 
> ```r
> NA
> ```
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_

While the workflow is fixed and I can pull QBR data manually via URL, the import_qbr function in nfl-data-py is still not pulling 2024 data. I believe this to be a result of it pointing to the incorrect data source.

**Comment by alecglen** [comment]
@StoneMasons4106 that's tracked here https://github.com/nflverse/nfl_data_py/issues/114
