### ISSUE TITLE
load_players should have all IDs from load_roster and load_ff_playerids

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflverse-data#7]
I believe we currently have it that IDs are joined onto load_rosters for backwards compat, but really our primary ID file should be load_players()

thoughts @john-b-edwards @mrcaseb ?

**Comment by tanho63** [comment]
We should make load_players the core for nflverse and tack on ff_playerids afterwards imo. This more or less fell through the cracks unfortunately

**Comment by mrcaseb** [comment]
Players data outsourced to https://github.com/nflverse/nflverse-players
