### ISSUE TITLE
Inconsistent team naming in `load_rosters()`

### ISSUE THREAD

**Issue by iorparask** [nflverse/nflverse-data#9]
When retrieving rosters using load_rosters(season), Oakland Raiders (OAK) are always missing from the returned records.
Applies to all seasons from 2013-2022.

**Comment by john-b-edwards** [comment]
The Raiders are in `load_rosters()`, they're just under "LV" and not "OAK".

```r
nflreadr::load_rosters(2015) |>
    dplyr::pull(team) |>
    table()
#> 
#> ARZ ATL BLT BUF CAR CHI CIN CLV DAL DEN DET  GB HST IND JAX  KC  LV MIA MIN  NE 
#>  56  56  61  59  55  60  53  57  66  58  59  54  61  55  54  54  56  58  55  61 
#>  NO NYG NYJ PHI PIT  SD SEA  SF  SL  TB TEN WAS 
#>  58  55  57  54  54  53  58  57  53  57  54  59
```

I'm realizing, however, that this is inconsistent with how we do rosters for other teams -- the Rams and Chargers are listed as "SD" and "SL" instead of "LAC" and "LA". @tanho63 should we swap LV to OAK for years for consistency's sake, or should we swap SD and SL to LAC and LA for continuity's sake?

**Comment by tanho63** [comment]
I lean having it as OAK for years it was in Oakland, clean_team_abbrs converts only in one direction (unifying to modern)

**Comment by tanho63** [comment]
What does Lee’s schedules file have?

**Comment by john-b-edwards** [comment]
It's in there as "OAK", though Lee's schedules has a fair number of inconsistencies with the existing rosters files (e.g. "ARI" instead of "ARZ", "STL" instead of "SL"), etc. NFL internal stuff is annoying inconsistent with the abbreviations so that's probably driving all this

**Comment by john-b-edwards** [comment]
This has been resolved:

```r
nflreadr::load_rosters(2013:2022) |>
    dplyr::filter(team %in% c("OAK","LV")) |>
    dplyr::group_by(season, team) |>
    dplyr::summarise(.groups="drop")
#> # A tibble: 10 × 2
#>    season team 
#>     <int> <chr>
#>  1   2013 OAK  
#>  2   2014 OAK  
#>  3   2015 OAK  
#>  4   2016 OAK  
#>  5   2017 OAK  
#>  6   2018 OAK  
#>  7   2019 OAK  
#>  8   2020 LV   
#>  9   2021 LV   
#> 10   2022 LV
```
